 import mongoose from "mongoose";
import dotenv from "dotenv";

import Tool from "./models/toolmodel.js";
import User from "./models/usermodels.js";

dotenv.config();

const seedTools = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URL);
    console.log("MongoDB Connected");

    const admin = await User.findOne({ role: "admin" });

    if (!admin) {
      throw new Error("Admin user not found. Create admin first.");
    }

    await Tool.deleteMany();

   const tools = [
 {
    name: "GitHub Copilot",
    description: "AI coding assistant",
    category: "Development",
    url: "https://github.com/features/copilot",
    field: "developers",
    createdBy: admin._id,
    status: "pending",
    targetAudience:"developers"
  },
  {
    name: "Replit",
    description: "Online coding platform",
    category: "Development",
    url: "https://replit.com",
    targetAudience: "students",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "CodePen",
    description: "Frontend playground",
    category: "Development",
    url: "https://codepen.io",
    targetAudience: "developers",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "StackBlitz",
    description: "Online IDE for full-stack apps",
    category: "Development",
    url: "https://stackblitz.com",
    targetAudience: "developers",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "JSFiddle",
    description: "Playground for web development",
    category: "Development",
    url: "https://jsfiddle.net",
    targetAudience: "developers",
    createdBy: admin._id,
    status: "pending",
  },



  {
    name: "ChatGPT",
    description: "AI text generation tool",
    category: "Text",
    url: "https://chat.openai.com",
    targetAudience: "students",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Canva",
    description: "Graphic design platform",
    category: "Design",
    url: "https://canva.com",
    targetAudience: "designers",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Notion",
    description: "All-in-one productivity workspace",
    category: "Productivity",
    url: "https://notion.so",
    targetAudience: "professionals",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Midjourney",
    description: "AI image generation tool",
    category: "Design",
    url: "https://midjourney.com",
    targetAudience: "creators",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Grammarly",
    description: "Writing assistant",
    category: "Text",
    url: "https://grammarly.com",
    targetAudience: "students",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "GitHub Copilot",
    description: "AI coding assistant",
    category: "Development",
    url: "https://github.com/features/copilot",
    targetAudience: "developers",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Figma",
    description: "UI/UX design tool",
    category: "Design",
    url: "https://figma.com",
    targetAudience: "designers",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Jasper AI",
    description: "Marketing content generator",
    category: "Marketing",
    url: "https://jasper.ai",
    targetAudience: "marketers",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Zapier",
    description: "Workflow automation tool",
    category: "Automation",
    url: "https://zapier.com",
    targetAudience: "professionals",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Trello",
    description: "Project management board",
    category: "Productivity",
    url: "https://trello.com",
    targetAudience: "teams",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "ClickUp",
    description: "Task and team management",
    category: "Productivity",
    url: "https://clickup.com",
    targetAudience: "teams",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Slack",
    description: "Team communication platform",
    category: "Communication",
    url: "https://slack.com",
    targetAudience: "teams",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Zoom",
    description: "Video conferencing tool",
    category: "Communication",
    url: "https://zoom.us",
    targetAudience: "professionals",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Descript",
    description: "AI audio and video editing",
    category: "Media",
    url: "https://descript.com",
    targetAudience: "creators",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Pictory",
    description: "Text to video AI tool",
    category: "Media",
    url: "https://pictory.ai",
    targetAudience: "marketers",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Surfer SEO",
    description: "SEO optimization tool",
    category: "Marketing",
    url: "https://surferseo.com",
    targetAudience: "marketers",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Ahrefs",
    description: "SEO analytics platform",
    category: "Marketing",
    url: "https://ahrefs.com",
    targetAudience: "professionals",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Ubersuggest",
    description: "Keyword research tool",
    category: "Marketing",
    url: "https://neilpatel.com/ubersuggest",
    targetAudience: "marketers",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Replit",
    description: "Online coding platform",
    category: "Development",
    url: "https://replit.com",
    targetAudience: "students",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "CodePen",
    description: "Frontend playground",
    category: "Development",
    url: "https://codepen.io",
    targetAudience: "developers",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Wordtune",
    description: "AI rewriting assistant",
    category: "Text",
    url: "https://wordtune.com",
    targetAudience: "writers",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Synthesia",
    description: "AI avatar video creator",
    category: "Media",
    url: "https://synthesia.io",
    targetAudience: "creators",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Copy.ai",
    description: "AI copywriting tool",
    category: "Text",
    url: "https://copy.ai",
    targetAudience: "marketers",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "QuillBot",
    description: "Paraphrasing tool",
    category: "Text",
    url: "https://quillbot.com",
    targetAudience: "students",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Calendly",
    description: "Meeting scheduling tool",
    category: "Productivity",
    url: "https://calendly.com",
    targetAudience: "professionals",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Loom",
    description: "Screen recording tool",
    category: "Media",
    url: "https://loom.com",
    targetAudience: "teams",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Obsidian",
    description: "Knowledge management app",
    category: "Productivity",
    url: "https://obsidian.md",
    targetAudience: "students",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Perplexity AI",
    description: "AI-powered search engine",
    category: "Research",
    url: "https://perplexity.ai",
    targetAudience: "researchers",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Claude AI",
    description: "Conversational AI assistant",
    category: "Text",
    url: "https://claude.ai",
    targetAudience: "professionals",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Runway ML",
    description: "AI video editing platform",
    category: "Media",
    url: "https://runwayml.com",
    targetAudience: "creators",
    createdBy: admin._id,
    status: "pending",
  },
 
  {
    name: "Jasper AI",
    description: "AI content generation platform",
    category: "Marketing",
    url: "https://jasper.ai",
    targetAudience: "marketers",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Grammarly",
    description: "AI writing assistant",
    category: "Text",
    url: "https://grammarly.com",
    targetAudience: "writers",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Midjourney",
    description: "AI image generation tool",
    category: "Design",
    url: "https://midjourney.com",
    targetAudience: "designers",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Figma AI",
    description: "AI-powered UI/UX design assistant",
    category: "Design",
    url: "https://figma.com",
    targetAudience: "designers",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Zapier AI",
    description: "Workflow automation AI",
    category: "Automation",
    url: "https://zapier.com",
    targetAudience: "professionals",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Copy.ai",
    description: "AI copywriting tool",
    category: "Marketing",
    url: "https://copy.ai",
    targetAudience: "marketers",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Replit AI",
    description: "AI coding assistant",
    category: "Development",
    url: "https://replit.com",
    targetAudience: "students",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "CodePen AI",
    description: "Frontend playground with AI suggestions",
    category: "Development",
    url: "https://codepen.io",
    targetAudience: "developers",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Wordtune",
    description: "AI rewriting assistant",
    category: "Text",
    url: "https://wordtune.com",
    targetAudience: "writers",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Synthesia",
    description: "AI avatar video creator",
    category: "Media",
    url: "https://synthesia.io",
    targetAudience: "creators",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Lumen5",
    description: "AI video creation tool",
    category: "Media",
    url: "https://lumen5.com",
    targetAudience: "marketers",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Perplexity AI",
    description: "AI-powered search engine",
    category: "Research",
    url: "https://perplexity.ai",
    targetAudience: "researchers",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Claude AI",
    description: "Conversational AI assistant",
    category: "Text",
    url: "https://claude.ai",
    targetAudience: "professionals",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Runway ML",
    description: "AI video editing platform",
    category: "Media",
    url: "https://runwayml.com",
    targetAudience: "creators",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Notion AI",
    description: "AI productivity assistant",
    category: "Productivity",
    url: "https://notion.so",
    targetAudience: "students",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "CopySmith",
    description: "AI content generator for e-commerce",
    category: "Marketing",
    url: "https://copysmith.ai",
    targetAudience: "marketers",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "ChatGPT",
    description: "AI conversational assistant",
    category: "Text",
    url: "https://chat.openai.com",
    targetAudience: "everyone",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Fireflies AI",
    description: "AI meeting assistant",
    category: "Productivity",
    url: "https://fireflies.ai",
    targetAudience: "teams",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Otter.ai",
    description: "AI transcription tool",
    category: "Productivity",
    url: "https://otter.ai",
    targetAudience: "students",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Pictory AI",
    description: "AI video summarization tool",
    category: "Media",
    url: "https://pictory.ai",
    targetAudience: "creators",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Descript",
    description: "AI audio & video editor",
    category: "Media",
    url: "https://descript.com",
    targetAudience: "creators",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Superhuman AI",
    description: "AI email productivity assistant",
    category: "Productivity",
    url: "https://superhuman.com",
    targetAudience: "professionals",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Ink AI",
    description: "AI writing & SEO assistant",
    category: "Marketing",
    url: "https://inkforall.com",
    targetAudience: "marketers",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Neural.love",
    description: "AI image & video generator",
    category: "Media",
    url: "https://neural.love",
    targetAudience: "creators",
    createdBy: admin._id,
    status: "pending",
  },
  {
    name: "Frase AI",
    description: "AI SEO content research tool",
    category: "Marketing",
    url: "https://frase.io",
    targetAudience: "marketers",
    createdBy: admin._id,
    status: "pending",
  },
];

 


    await Tool.insertMany(tools);

    console.log("✅ Tools seeded successfully");
    process.exit();
  } catch (error) {
    console.error("❌ Seeding error:", error.message);
    process.exit(1);
  }
};

// 🔥 THIS WAS MISSING
seedTools();
